spring:

  devtools:
    restart:
      enabled: true

  freemarker:
    cache: false # 是否启用缓存

  datasource:
    name: test
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: org.elasticsearch.xpack.sql.jdbc.jdbc.JdbcDriver
    username: root
    password: 123456
    url: jdbc:mysql://10.0.0.2/blog?characterEncoding=utf-8&useSSL=false&autoReconnect=true
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


# 自己的配置项
blog:
  desKey: cvV8Mq7IIWc1IeOpeHenLVKouhXYyXog
